services:
  backend:
    container_name: nft-service
    image: nft-service:1.0.1
    restart: unless-stopped
    build:
      dockerfile: backend.Dockerfile
    ports:
      - '3010:3010'
    networks:
      - nft-network
    environment:
      - APP_ADDR=${APP_ADDR}
      - APP_DEBUG=${APP_DEBUG}
      - IPFS_API_URL=${IPFS_API_URL}
      - IPFS_GATEWAY_URL=${IPFS_GATEWAY_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_AUTH_EXPIRED=${JWT_AUTH_EXPIRED}
      - JWT_REFRESH_EXPIRED=${JWT_REFRESH_EXPIRED}
      - APP_SECRET=${APP_SECRET}
      - DB_URI=${DB_URI}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - LOG_LEVEL=${LOG_LEVEL}

networks:
  nft-network:
    external: true

