version: '3.8'

services:
  app:
    build:
      context: .
    container_name: nft-admin-app
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      - nft-network

networks:
  nft-network:
    external: true